language: python
cache: pip
dist: xenial

python:
  - "3.6"
  - "3.7"

before_install:
  - pip install pip --upgrade

install:
  - pip install -e .[tests,models]

script:
  - pytest --cov -rfsxEX
  - pytest -rfsxEX --nbval ./notebooks --sanitize ./notebooks/tests_sanitize.cfg

after_success:
  - codecov
